### ISSUE TITLE
ERROR JSON!!

### ISSUE THREAD

**Issue by kndalf** [cognits/frontend-angularjs#1]
hola buenas tardes encontre un codigo para leer json pero tengo un problema , logre hacerlo con un json siempre local que yo mismo modifique para que por lo menos quedara dentro de un diccionario otra lista , ![GitHub Logo](http://s2.subirimagenes.com/imagen/previo/thump_9251163captura-de-pantalla.png)

este  es el error que me muestra con el json dado en el proyecto con este tengo el problema

y este otro json siempre local y si funciona 
el otro json
![GitHub Logo](http://s2.subirimagenes.com/imagen/previo/thump_9251198captura-de-pantalla.png)

**Comment by sebasibarguen** [comment]
Gracias Brandon, ya fue arreglado.
